name: RPM Build (Fedora 40)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v2

    - name: Get RPM Spec BuildDepends
      run: dnf builddep fedora-kernel-manager.spec"

    - name: Build RPM package
      run: rpmbuild -bb fedora-kernel-manager.spec --define "_rpmdir $(pwd)/packages

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: packages/*.rpm
